[package]
name = "gpurec-preprocess"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["abi3-py310", "extension-module"] }
rustree = { git = "https://github.com/SisyphusMountain/rustree.git", rev = "e3a58478f0e57c80af04c730acade639d8e9015e" }
serde_json = "1"
